In [23]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)


In [24]:
from google.colab import files

img_arr1 = files.upload()


Saving bobby.jpg to bobby.jpg


In [25]:
img_arr = torch.Tensor(img_arr1)

TypeError: ignored

In [ ]:
img_arr1.shape

In [ ]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)

In [ ]:
batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)

In [26]:
import os

data_dir = '../data/p1ch4/image-cats/'
filenames = [name for name in os.listdir(data_dir)
             if os.path.splitext(name)[-1] == '.png']
for i, filename in enumerate(filenames):
    img_arr = imageio.imread(os.path.join(data_dir, filename))
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3] 
    batch[i] = img_t

FileNotFoundError: ignored

In [27]:
#의료용 영상 처리하기
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50)

In [28]:
import imageio
from google.colab import drive

drive.mount("../pytorchdeeplearningmaster/data/p1ch4/volumetric-dicom/2-LUNG_3.0_B70f-04083")
dir_path = "../data/p1ch4/volumetric-dicom/2-LUNG_3.0_B70f-04083"
vol_arr = imageio.volread(dir_path, 'DICOM')
vol_arr.shape

ValueError: ignored

In [29]:
vol = torch.from_numpy(vol_arr).float()
vol = torch.unsqueeze(vol, 0)

vol.shape

NameError: ignored

In [30]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.imshow(vol_arr[50])

NameError: ignored

In [31]:
#실제 와인 데이터셋으로 진행해보자 !
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, precision=2, linewidth=75)

In [34]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, precision=2, linewidth=75)
import csv

drive.mount('../pytorchdeeplearningmaster/data/p1ch4/tabular-wine/winequality-white.csv')
wine_path = "../data/p1ch4/tabular-wine/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";",
                         skiprows=1)
wineq_numpy

ValueError: ignored

In [35]:
col_list = next(csv.reader(open(wine_path), delimiter=';'))

wineq_numpy.shape, col_list

FileNotFoundError: ignored

In [36]:
wineq = torch.from_numpy(wineq_numpy)

wineq.shape, wineq.dtype

NameError: ignored

In [38]:
data = wineq[:, :-1] 
data, data.shape

NameError: ignored

In [39]:
target = wineq[:, -1] # <2>
target, target.shape

NameError: ignored

In [40]:
target = wineq[:, -1].long()
target

NameError: ignored

In [41]:
target_onehot = torch.zeros(target.shape[0], 10)

target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

NameError: ignored

In [42]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed

NameError: ignored

In [43]:
data_mean = torch.mean(data, dim=0)
data_mean

NameError: ignored

In [44]:
data_var = torch.var(data, dim=0)
data_var

NameError: ignored

In [45]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

NameError: ignored

In [46]:

bad_indexes = target <= 3 # <1>
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

NameError: ignored

In [47]:
bad_data = data[bad_indexes]
bad_data.shape

NameError: ignored

In [48]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)] # <1>
good_data = data[target >= 7]

bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print('{:2} {:20} {:6.2f} {:6.2f} {:6.2f}'.format(i, *args))

NameError: ignored

In [49]:
total_sulfur_threshold = 141.83
total_sulfur_data = data[:,6]
predicted_indexes = torch.lt(total_sulfur_data, total_sulfur_threshold)

predicted_indexes.shape, predicted_indexes.dtype, predicted_indexes.sum()

NameError: ignored

In [50]:
actual_indexes = target > 5

actual_indexes.shape, actual_indexes.dtype, actual_indexes.sum()

NameError: ignored

In [51]:
n_matches = torch.sum(actual_indexes & predicted_indexes).item()
n_predicted = torch.sum(predicted_indexes).item()
n_actual = torch.sum(actual_indexes).item()

n_matches, n_matches / n_predicted, n_matches / n_actual

NameError: ignored

In [52]:
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, threshold=50, linewidth=75)

In [65]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
bikes_numpy = pd.read_csv(
    "/content/drive/MyDrive/pytorchdeeplearningmaster/data/p1ch4/bike-sharing-dataset/hour-fixed.csv", 
    dtype=np.float32, 
    delimiter=",", 
    skiprows=1, 
    converters={1: lambda x: float(x[8:10])}) # <1>



Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


/usr/local/lib/python3.9/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Both a converter and dtype were specified for column 2011-01-01 - only the converter will be used.
  return func(*args, **kwargs)


In [71]:
bikes_numpy = np.loadtxt("/content/drive/MyDrive/pytorchdeeplearningmaster/data/p1ch4/bike-sharing-dataset/hour-fixed.csv", 
    dtype=np.float32, 
    delimiter=",", 
    skiprows=1, 
    converters={1: lambda x: float(x[8:10])})
bikes = torch.from_numpy(bikes_numpy)
bikes

tensor([[1.00e+00, 1.00e+00,  ..., 1.30e+01, 1.60e+01],
        [2.00e+00, 1.00e+00,  ..., 3.20e+01, 4.00e+01],
        ...,
        [1.74e+04, 3.10e+01,  ..., 4.80e+01, 6.10e+01],
        [1.74e+04, 3.10e+01,  ..., 3.70e+01, 4.90e+01]])

In [72]:
bikes.shape, bikes.stride()

(torch.Size([17520, 17]), (17, 1))

In [73]:
daily_bikes = bikes.view(-1, 24, bikes.shape[1])
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 24, 17]), (408, 17, 1))

In [74]:
daily_bikes = daily_bikes.transpose(1, 2)
daily_bikes.shape, daily_bikes.stride()

(torch.Size([730, 17, 24]), (408, 1, 17))

In [75]:
#첫 날의 데이터만을 생각!
first_day = bikes[:24].long()
weather_onehot = torch.zeros(first_day.shape[0], 4)
first_day[:,9]

tensor([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 2, 2,
        2, 2])

In [77]:
#날씨 수준에 따라 행렬을 원핫 인코딩으로 변환, unsqueeze를 사용해 싱글톤 차원 더하기
weather_onehot.scatter_(
    dim=1, 
    index=first_day[:,9].unsqueeze(1).long() - 1,
    value=1.0)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        ...,
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]])

In [78]:
#만들어진 행렬을 원래 데이터셋에 cat 함수를 사용하여 병합하기
torch.cat((bikes[:24], weather_onehot), 1)[:1]

tensor([[ 1.00,  1.00,  1.00,  0.00,  1.00,  0.00,  0.00,  6.00,  0.00,
          1.00,  0.24,  0.29,  0.81,  0.00,  3.00, 13.00, 16.00,  1.00,
          0.00,  0.00,  0.00]])

In [80]:
# 데이터는 (B,C,L)형태, L=24시간 !, 추가 열의 크기는 C인 텐서를 만들자.
daily_weather_onehot = torch.zeros(daily_bikes.shape[0], 4,
                                   daily_bikes.shape[2])
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [81]:
#텐서의 C차원에 원핫 인코딩을 늘어놓자. (텐서안 수행이므로 텐서 내용이 바뀜)
daily_weather_onehot.scatter_(
    1, daily_bikes[:,9,:].long().unsqueeze(1) - 1, 1.0)
daily_weather_onehot.shape

torch.Size([730, 4, 24])

In [82]:
#C 차원을 따라 원핫 인코딩을 병합하자
daily_bikes = torch.cat((daily_bikes, daily_weather_onehot), dim=1)

In [83]:
#값의 범위 매핑하기, 특정 값으로 바꾸기
daily_bikes[:, 9, :] = (daily_bikes[:, 9, :] - 1.0) / 3.0

In [84]:
temp = daily_bikes[:, 10, :]
temp_min = torch.min(temp)
temp_max = torch.max(temp)
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - temp_min)
                         / (temp_max - temp_min))

In [85]:
temp = daily_bikes[:, 10, :]
daily_bikes[:, 10, :] = ((daily_bikes[:, 10, :] - torch.mean(temp))
                         / torch.std(temp))
#표준편차로 나누는방법

## **텍스트 처리하기**